version: "3.8"
services:
  web:
    build:
      context: ./
      target: production
    # command: npm start
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/var/log
    environment:
      NODE_ENV: production
    env_file:
      - .env
